### ISSUE TITLE
Search on https://docs.flame-engine.org/ is broken

### ISSUE THREAD

**Issue by Unifex** [flame-engine/flame-docs-site#8] opened 2022-10-03 05:23 UTC
The error can be seen [here](https://docs.flame-engine.org/1.4.0/search.html?q=HasWidgetsOverlay) but it works with any search term.

Looking at the error I suspect it isn't actually search that is at fault, but the highlighting sphinx provides. It looks to be crashing the JS preventing search from completing.

![Screenshot 2022-10-03 181851](https://user-images.githubusercontent.com/238424/193506420-c53c8fe1-a848-40e3-9500-1eac895f484c.png)

**Comment by spydon** [comment] 2022-10-03 06:41
Duplicate of https://github.com/flame-engine/flame/issues/1999
(This repository is just used to contain the result of generating the docs)

**Closed by spydon** 2022-10-03 06:41 UTC
